/**
 * Mock data for dev preview mode (NEXT_PUBLIC_DEV_PREVIEW=true).
 * Provides realistic sample data when Supabase is unavailable.
 */

import type {
  Lead,
  Application,
  Experience,
  Session,
  LeadActivity,
  AthleteMetrics,
  ScheduleSlotEnriched,
} from '@/types'
import type { ApplicationWithLead } from '@/hooks/useApplications'
import type { SessionEnriched } from '@/types'

const now = new Date()
const today = now.toISOString().split('T')[0]
const yesterday = new Date(now.getTime() - 86400000).toISOString().split('T')[0]
const twoDaysAgo = new Date(now.getTime() - 2 * 86400000).toISOString().split('T')[0]
const threeDaysAgo = new Date(now.getTime() - 3 * 86400000).toISOString().split('T')[0]
const nextWeek = new Date(now.getTime() + 7 * 86400000).toISOString().split('T')[0]
const nextWeekEnd = new Date(now.getTime() + 10 * 86400000).toISOString().split('T')[0]
const twoWeeks = new Date(now.getTime() + 14 * 86400000).toISOString().split('T')[0]
const twoWeeksEnd = new Date(now.getTime() + 17 * 86400000).toISOString().split('T')[0]
const lastWeek = new Date(now.getTime() - 7 * 86400000).toISOString().split('T')[0]
const lastWeekEnd = new Date(now.getTime() - 4 * 86400000).toISOString().split('T')[0]

export const MOCK_LEADS: Lead[] = [
  {
    id: 'lead-001',
    ghl_contact_id: 'ghl-001',
    contact_name: 'Mike Thompson',
    contact_phone: '+16155551234',
    contact_email: 'mike.thompson@email.com',
    athlete_name: 'Jake Thompson',
    athlete_age: 16,
    athlete_position: 'RHP/SS',
    athlete_level: 'high_school',
    athlete_velocity: '82 mph',
    athlete_school_team: 'Farragut HS',
    location: 'Knoxville, TN',
    distance_hours: 0,
    lead_temperature: 'hot',
    fit_score: 'good_fit',
    service_match: '108_experience',
    intent: 'ready_to_book',
    queue: 'call_now',
    priority: 95,
    ai_summary: 'Junior RHP at Farragut HS throwing 82 mph. Dad reached out about the 108 Experience after seeing results from a teammate. Ready to book for spring break. Strong fit.',
    original_message: 'Hi, my son Jake is a junior pitcher at Farragut. His teammate did the 108 Experience last summer and gained 5 mph. We want to book for spring break if possible.',
    suggested_response: 'Great to hear about Jake! We love working with Farragut athletes. Spring break slots are filling up — let me get you on the calendar.',
    channel: 'web_form',
    tags: ['pitcher', 'farragut', 'spring_break'],
    status: 'new',
    claimed_by: null,
    claimed_at: null,
    call_outcome: null,
    call_notes: null,
    call_duration: null,
    follow_up_date: null,
    pipeline_stage: 'lead',
    inbound_at: new Date(now.getTime() - 3600000).toISOString(),
    created_at: new Date(now.getTime() - 3600000).toISOString(),
    updated_at: new Date(now.getTime() - 3600000).toISOString(),
  },
  {
    id: 'lead-002',
    ghl_contact_id: 'ghl-002',
    contact_name: 'Sarah Williams',
    contact_phone: '+16155552345',
    contact_email: 'sarah.w@gmail.com',
    athlete_name: 'Emma Williams',
    athlete_age: 14,
    athlete_position: 'OF/Slapper',
    athlete_level: 'middle_school',
    athlete_velocity: null,
    athlete_school_team: 'TN Fury 14U',
    location: 'Maryville, TN',
    distance_hours: 0.5,
    lead_temperature: 'warm',
    fit_score: 'good_fit',
    service_match: 'tri_star',
    intent: 'has_questions',
    queue: 'follow_up',
    priority: 70,
    ai_summary: '14U travel ball player, primarily a slapper/outfielder. Mom wants to improve hitting mechanics. Asking about Tri-Star program pricing.',
    original_message: 'Looking for hitting instruction for my daughter. She plays travel ball and needs help with her slap game. What programs do you offer?',
    suggested_response: 'The Tri-Star program would be perfect for Emma! We focus on both rotational and slap mechanics. Let me send you program details.',
    channel: 'facebook',
    tags: ['softball', 'hitting', 'travel_ball'],
    status: 'claimed',
    claimed_by: 'user-jose',
    claimed_at: yesterday + 'T14:00:00Z',
    claimed_by_name: 'Jose',
    call_outcome: null,
    call_notes: null,
    call_duration: null,
    follow_up_date: today,
    pipeline_stage: 'lead',
    inbound_at: yesterday + 'T10:00:00Z',
    created_at: yesterday + 'T10:00:00Z',
    updated_at: yesterday + 'T14:00:00Z',
  },
  {
    id: 'lead-003',
    ghl_contact_id: 'ghl-003',
    contact_name: 'David Chen',
    contact_phone: '+16155553456',
    contact_email: 'dchen@utk.edu',
    athlete_name: 'Ryan Chen',
    athlete_age: 19,
    athlete_position: 'RHP',
    athlete_level: 'college',
    athlete_velocity: '91 mph',
    athlete_school_team: 'UT Club Baseball',
    location: 'Knoxville, TN',
    distance_hours: 0,
    lead_temperature: 'hot',
    fit_score: 'good_fit',
    service_match: 'college_prep',
    intent: 'ready_to_book',
    queue: 'call_now',
    priority: 90,
    ai_summary: 'College club player at UT, throwing 91 mph. Looking to walk on to varsity. Wants velocity and mechanics work. High-level prospect.',
    original_message: 'I pitch for UT club baseball and want to try walking on. Currently sitting 89-91. Need to get to 93+. Heard you guys are the best in the area.',
    suggested_response: 'Ryan, we love that goal. Several of our guys have made the jump from club to varsity. Let\'s talk about a custom program.',
    channel: 'referral',
    tags: ['college', 'velocity', 'walk_on'],
    status: 'contacted',
    claimed_by: 'user-greg',
    claimed_at: twoDaysAgo + 'T09:00:00Z',
    claimed_by_name: 'Greg',
    call_outcome: 'follow_up_scheduled',
    call_notes: 'Spoke with Ryan. Very motivated. Wants to start ASAP. Scheduling for next week.',
    call_duration: 18,
    follow_up_date: today,
    pipeline_stage: 'applied',
    inbound_at: threeDaysAgo + 'T16:00:00Z',
    created_at: threeDaysAgo + 'T16:00:00Z',
    updated_at: yesterday + 'T11:00:00Z',
  },
  {
    id: 'lead-004',
    ghl_contact_id: 'ghl-004',
    contact_name: 'Jennifer Davis',
    contact_phone: '+16155554567',
    contact_email: 'jdavis@yahoo.com',
    athlete_name: 'Tyler Davis',
    athlete_age: 12,
    athlete_position: 'C/3B',
    athlete_level: 'youth',
    athlete_velocity: null,
    athlete_school_team: 'Powell Middle School',
    location: 'Powell, TN',
    distance_hours: 0.3,
    lead_temperature: 'cold',
    fit_score: 'maybe',
    service_match: 'unknown',
    intent: 'just_browsing',
    queue: 'nurture',
    priority: 30,
    ai_summary: '12-year-old catcher/3B. Mom browsing options. Not ready to commit but interested in summer camps.',
    original_message: 'What kind of baseball training do you offer for younger kids? My son is 12.',
    suggested_response: 'We\'d love to help Tyler! For his age, our youth development program focuses on fundamentals and fun.',
    channel: 'google',
    tags: ['youth', 'summer'],
    status: 'new',
    claimed_by: null,
    claimed_at: null,
    call_outcome: null,
    call_notes: null,
    call_duration: null,
    follow_up_date: null,
    pipeline_stage: 'lead',
    inbound_at: yesterday + 'T20:00:00Z',
    created_at: yesterday + 'T20:00:00Z',
    updated_at: yesterday + 'T20:00:00Z',
  },
  {
    id: 'lead-005',
    ghl_contact_id: 'ghl-005',
    contact_name: 'Robert Martinez',
    contact_phone: '+16155555678',
    contact_email: 'rmartinez@email.com',
    athlete_name: 'Carlos Martinez',
    athlete_age: 17,
    athlete_position: 'LHP/OF',
    athlete_level: 'high_school',
    athlete_velocity: '85 mph',
    athlete_school_team: 'Bearden HS',
    location: 'Knoxville, TN',
    distance_hours: 0,
    lead_temperature: 'hot',
    fit_score: 'good_fit',
    service_match: '108_experience',
    intent: 'ready_to_book',
    queue: 'call_now',
    priority: 92,
    ai_summary: 'Senior LHP at Bearden, 85 mph. Being recruited by D2 schools. Wants the 108 Experience before senior showcase season.',
    original_message: 'Carlos is a senior lefty at Bearden. He has a few D2 offers but wants to showcase better. Can we do the 108 Experience before March?',
    suggested_response: 'Carlos sounds like an excellent fit! Let me check our February availability for the 108 Experience.',
    channel: 'phone',
    tags: ['lefty', 'senior', 'recruiting'],
    status: 'converted',
    claimed_by: 'user-jose',
    claimed_at: lastWeek + 'T10:00:00Z',
    claimed_by_name: 'Jose',
    call_outcome: 'booked',
    call_notes: 'Booked 108 Experience for next week. Deposit paid. Very excited.',
    call_duration: 25,
    follow_up_date: null,
    pipeline_stage: 'booked',
    inbound_at: lastWeek + 'T08:00:00Z',
    created_at: lastWeek + 'T08:00:00Z',
    updated_at: yesterday + 'T09:00:00Z',
  },
  {
    id: 'lead-006',
    ghl_contact_id: 'ghl-006',
    contact_name: 'Amanda Foster',
    contact_phone: '+16155556789',
    contact_email: 'afoster@email.com',
    athlete_name: 'Lily Foster',
    athlete_age: 15,
    athlete_position: 'RHP/1B',
    athlete_level: 'high_school',
    athlete_velocity: '58 mph',
    athlete_school_team: 'Webb School',
    location: 'Knoxville, TN',
    distance_hours: 0,
    lead_temperature: 'warm',
    fit_score: 'good_fit',
    service_match: '108_experience',
    intent: 'has_questions',
    queue: 'follow_up',
    priority: 65,
    ai_summary: 'Sophomore softball pitcher at Webb. Looking for velocity and spin rate improvement. Family can afford premium programs.',
    original_message: 'My daughter pitches for Webb School. She wants to throw harder and get more movement. What do you recommend?',
    suggested_response: 'Lily could really benefit from our pitching-focused 108 Experience! Webb athletes have done great with us.',
    channel: 'instagram',
    tags: ['softball', 'pitcher', 'webb'],
    status: 'claimed',
    claimed_by: 'user-jose',
    claimed_at: today + 'T08:00:00Z',
    claimed_by_name: 'Jose',
    call_outcome: null,
    call_notes: null,
    call_duration: null,
    follow_up_date: today,
    pipeline_stage: 'lead',
    inbound_at: yesterday + 'T15:00:00Z',
    created_at: yesterday + 'T15:00:00Z',
    updated_at: today + 'T08:00:00Z',
  },
]

export const MOCK_APPLICATIONS: ApplicationWithLead[] = [
  {
    id: 'app-001',
    lead_id: 'lead-003',
    status: 'submitted',
    submitted_at: yesterday + 'T14:00:00Z',
    review_notes: undefined,
    decision_reason: undefined,
    video_url: 'https://youtube.com/watch?v=example1',
    responses: {
      training_goals: 'Walk-on to UT varsity. Need to gain 3-4 mph and improve breaking ball.',
      current_team: 'UT Club Baseball',
      how_heard: 'Referral from former 108 athlete',
      injury_history: 'None',
      parent_guardian: 'Self (19 years old)',
    },
    created_at: yesterday + 'T14:00:00Z',
    updated_at: yesterday + 'T14:00:00Z',
    athlete_name: 'Ryan Chen',
    contact_name: 'David Chen',
    contact_phone: '+16155553456',
    athlete_level: 'college',
    athlete_age: 19,
    lead_temperature: 'hot',
  },
  {
    id: 'app-002',
    lead_id: 'lead-005',
    status: 'accepted',
    submitted_at: lastWeek + 'T12:00:00Z',
    reviewed_by: 'user-greg',
    reviewed_at: lastWeek + 'T16:00:00Z',
    review_notes: 'Strong candidate. Senior LHP with D2 offers. Excellent fit for 108 Experience.',
    decision_reason: 'Level, velocity, and goals align perfectly with our program.',
    video_url: 'https://youtube.com/watch?v=example2',
    responses: {
      training_goals: 'Increase velocity from 85 to 88+ for senior showcase season',
      current_team: 'Bearden HS Varsity',
      how_heard: 'Phone call inquiry',
      injury_history: 'Minor elbow soreness sophomore year, fully recovered',
      parent_guardian: 'Robert Martinez (father)',
    },
    created_at: lastWeek + 'T12:00:00Z',
    updated_at: lastWeek + 'T16:00:00Z',
    athlete_name: 'Carlos Martinez',
    contact_name: 'Robert Martinez',
    contact_phone: '+16155555678',
    athlete_level: 'high_school',
    athlete_age: 17,
    lead_temperature: 'hot',
  },
  {
    id: 'app-003',
    lead_id: 'lead-006',
    status: 'under_review',
    submitted_at: today + 'T09:00:00Z',
    review_notes: undefined,
    video_url: undefined,
    responses: {
      training_goals: 'Improve velocity and pitch movement for varsity season',
      current_team: 'Webb School Varsity Softball',
      how_heard: 'Instagram',
      injury_history: 'None',
      parent_guardian: 'Amanda Foster (mother)',
    },
    created_at: today + 'T09:00:00Z',
    updated_at: today + 'T09:00:00Z',
    athlete_name: 'Lily Foster',
    contact_name: 'Amanda Foster',
    contact_phone: '+16155556789',
    athlete_level: 'high_school',
    athlete_age: 15,
    lead_temperature: 'warm',
  },
]

export const MOCK_EXPERIENCES: Experience[] = [
  {
    id: 'exp-001',
    lead_id: 'lead-005',
    application_id: 'app-002',
    start_date: nextWeek,
    end_date: nextWeekEnd,
    skill_focus: 'pitching',
    duration_days: 4,
    price_cents: 250000,
    payment_status: 'deposit_paid',
    deposit_amount_cents: 75000,
    balance_due_cents: 175000,
    status: 'booked',
    notes: 'Senior LHP. Focus on velocity and breaking ball development.',
    created_at: yesterday + 'T10:00:00Z',
    updated_at: yesterday + 'T10:00:00Z',
  },
  {
    id: 'exp-002',
    lead_id: 'lead-001',
    start_date: twoWeeks,
    end_date: twoWeeksEnd,
    skill_focus: 'two_way',
    duration_days: 4,
    price_cents: 250000,
    payment_status: 'pending',
    status: 'booked',
    notes: 'Spring break slot. Two-way player.',
    created_at: today + 'T08:00:00Z',
    updated_at: today + 'T08:00:00Z',
  },
  {
    id: 'exp-003',
    lead_id: 'lead-003',
    start_date: lastWeek,
    end_date: lastWeekEnd,
    skill_focus: 'pitching',
    duration_days: 4,
    price_cents: 300000,
    payment_status: 'paid_full',
    status: 'completed',
    notes: 'College arm. Focused on velo and movement patterns.',
    created_at: lastWeek + 'T07:00:00Z',
    updated_at: yesterday + 'T17:00:00Z',
  },
]

export const MOCK_SESSIONS: SessionEnriched[] = [
  {
    id: 'sess-001',
    schedule_slot_id: 'slot-001',
    lead_id: 'lead-003',
    coach_id: 'coach-matt',
    date: yesterday,
    skill: 'pitching',
    duration_minutes: 90,
    raw_notes: 'Ryan showed excellent arm action today. Fastball sitting 89-91, touched 92 on the last set. Worked on slider grip — got 2 really good ones with 2800+ rpm. Need to continue working on consistency of breaking ball release point.',
    parsed_notes: {
      drills: ['Towel drill', 'Flat ground progressions', 'Bullpen — 35 pitches'],
      observations: ['Fastball velocity up from baseline', 'Slider showing good tilt', 'Release point slightly inconsistent on breaking ball'],
      cues_that_worked: ['Drive through the rubber', 'Stay tall at apex'],
      recommendations: ['Continue slider work next session', 'Add changeup introduction day 3'],
      concerns: [],
    },
    energy_level: 9,
    focus_areas: ['velocity', 'slider'],
    cues_that_worked: ['Drive through the rubber', 'Stay tall at apex'],
    is_exit_eval: false,
    note_mode: 'extended',
    coach_sentiment: 'green',
    sentiment_reason: 'Excellent session. Ryan is dialed in and making fast progress.',
    drills_performed: ['Towel drill', 'Flat ground', 'Bullpen'],
    key_observations: 'Velocity up, slider developing nicely',
    cues_given: 'Drive through rubber, stay tall at apex, pull down on slider',
    recommendations: 'Introduce changeup on day 3',
    athlete_effort_rating: 5,
    injury_notes: undefined,
    ai_parsed_at: yesterday + 'T18:00:00Z',
    created_at: yesterday + 'T17:00:00Z',
    updated_at: yesterday + 'T18:00:00Z',
    coach_name: 'Matt Reynolds',
    athlete_name: 'Ryan Chen',
    contact_name: 'David Chen',
  },
  {
    id: 'sess-002',
    schedule_slot_id: 'slot-002',
    lead_id: 'lead-003',
    coach_id: 'coach-matt',
    date: twoDaysAgo,
    skill: 'pitching',
    duration_minutes: 90,
    raw_notes: 'Day 1 assessment. Ryan came in throwing 89-90. Solid mechanics overall but some energy leak in lower half. Discussed goals and plan for the week.',
    parsed_notes: {
      drills: ['Assessment bullpen — 25 pitches', 'Video analysis', 'Mobility screening'],
      observations: ['Baseline velocity 89-90 mph', 'Good arm path', 'Energy leak in stride'],
      cues_that_worked: ['Lead with the hip'],
      recommendations: ['Address stride mechanics day 2', 'Start slider work'],
      concerns: [],
    },
    energy_level: 8,
    is_exit_eval: false,
    note_mode: 'quick',
    coach_sentiment: 'green',
    sentiment_reason: 'Good baseline session. Athlete is coachable and engaged.',
    drills_performed: ['Assessment bullpen', 'Video analysis'],
    athlete_effort_rating: 4,
    ai_parsed_at: twoDaysAgo + 'T18:00:00Z',
    created_at: twoDaysAgo + 'T17:00:00Z',
    updated_at: twoDaysAgo + 'T18:00:00Z',
    coach_name: 'Matt Reynolds',
    athlete_name: 'Ryan Chen',
    contact_name: 'David Chen',
  },
  {
    id: 'sess-003',
    schedule_slot_id: 'slot-003',
    lead_id: 'lead-005',
    coach_id: 'coach-drew',
    date: today,
    skill: 'hitting',
    duration_minutes: 60,
    raw_notes: 'Carlos looked great in the cage. Bat speed measured at 72 mph — above average for his age. Worked on keeping hands inside on inside pitches.',
    is_exit_eval: false,
    note_mode: 'quick',
    coach_sentiment: 'yellow',
    sentiment_reason: 'Good session overall but Carlos seemed a bit distracted. May be stressed about recruiting.',
    drills_performed: ['Tee work', 'Front toss', 'Live BP'],
    athlete_effort_rating: 3,
    created_at: today + 'T14:00:00Z',
    updated_at: today + 'T14:00:00Z',
    coach_name: 'Drew Anderson',
    athlete_name: 'Carlos Martinez',
    contact_name: 'Robert Martinez',
  },
]

export const MOCK_ACTIVITIES: LeadActivity[] = [
  { id: 'act-001', lead_id: 'lead-001', user_id: null, action: 'lead_created', details: { channel: 'web_form', temperature: 'hot' }, created_at: new Date(now.getTime() - 3600000).toISOString(), user_name: 'System' },
  { id: 'act-002', lead_id: 'lead-006', user_id: 'user-jose', action: 'lead_claimed', details: null, created_at: today + 'T08:00:00Z', user_name: 'Jose' },
  { id: 'act-003', lead_id: 'lead-003', user_id: 'user-greg', action: 'application_reviewed', details: { decision: 'submitted' }, created_at: yesterday + 'T14:30:00Z', user_name: 'Greg' },
  { id: 'act-004', lead_id: 'lead-005', user_id: 'user-jose', action: 'experience_booked', details: { skill_focus: 'pitching', duration_days: 4 }, created_at: yesterday + 'T10:00:00Z', user_name: 'Jose' },
  { id: 'act-005', lead_id: 'lead-003', user_id: 'coach-matt', action: 'session_created', details: { skill: 'pitching', sentiment: 'green' }, created_at: yesterday + 'T17:00:00Z', user_name: 'Matt Reynolds' },
  { id: 'act-006', lead_id: 'lead-002', user_id: 'user-jose', action: 'call_logged', details: { outcome: 'follow_up_scheduled' }, created_at: yesterday + 'T14:00:00Z', user_name: 'Jose' },
  { id: 'act-007', lead_id: 'lead-005', user_id: null, action: 'stage_changed', details: { from: 'applied', to: 'booked' }, created_at: yesterday + 'T10:30:00Z', user_name: 'System' },
  { id: 'act-008', lead_id: 'lead-004', user_id: null, action: 'lead_created', details: { channel: 'google', temperature: 'cold' }, created_at: yesterday + 'T20:00:00Z', user_name: 'System' },
]

export const MOCK_COACHES = [
  { id: 'coach-matt', name: 'Matt Reynolds', email: 'matt@108performance.com', role: 'coach' as const, coach_tier: 'S1' as const, disciplines: ['pitching', 'velocity'], notify_sms: true, notify_discord: true, is_coach: true, ghl_user_id: null, phone: '+16155559001', created_at: '2024-01-01T00:00:00Z' },
  { id: 'coach-drew', name: 'Drew Anderson', email: 'drew@108performance.com', role: 'coach' as const, coach_tier: 'S1' as const, disciplines: ['hitting', 'pitching'], notify_sms: true, notify_discord: true, is_coach: true, ghl_user_id: null, phone: '+16155559002', created_at: '2024-01-01T00:00:00Z' },
  { id: 'coach-austin', name: 'Austin Blake', email: 'austin@108performance.com', role: 'coach' as const, coach_tier: 'S2' as const, disciplines: ['pitching'], notify_sms: false, notify_discord: true, is_coach: true, ghl_user_id: null, phone: '+16155559003', created_at: '2024-01-01T00:00:00Z' },
  { id: 'coach-tyler', name: 'Tyler Morgan', email: 'tyler@108performance.com', role: 'coach' as const, coach_tier: 'S2' as const, disciplines: ['hitting', 'fielding'], notify_sms: false, notify_discord: true, is_coach: true, ghl_user_id: null, phone: '+16155559004', created_at: '2024-01-01T00:00:00Z' },
  { id: 'coach-jake', name: 'Jake Lawson', email: 'jake@108performance.com', role: 'coach' as const, coach_tier: 'J1' as const, disciplines: ['hitting'], notify_sms: false, notify_discord: false, is_coach: true, ghl_user_id: null, phone: '+16155559005', created_at: '2024-01-01T00:00:00Z' },
]

export const MOCK_PIPELINE_LEADS: Lead[] = MOCK_LEADS.map((l) => ({ ...l }))

export const MOCK_SCHEDULE_SLOTS: ScheduleSlotEnriched[] = [
  {
    id: 'slot-001',
    experience_id: 'exp-003',
    lead_id: 'lead-003',
    coach_id: 'coach-matt',
    date: yesterday,
    time_block: 'morning',
    skill: 'pitching',
    day_number: 3,
    is_final_day: false,
    status: 'completed',
    created_at: lastWeek + 'T07:00:00Z',
    updated_at: yesterday + 'T17:00:00Z',
    coach_name: 'Matt Reynolds',
    coach_tier_display: 'S1',
    athlete_name: 'Ryan Chen',
    contact_name: 'David Chen',
    contact_phone: '+16155553456',
    athlete_age: 19,
    athlete_level: 'college',
    experience_start: lastWeek,
    experience_end: lastWeekEnd,
    skill_focus: 'pitching',
    experience_status: 'completed',
    duration_days: 4,
  },
  {
    id: 'slot-002',
    experience_id: 'exp-003',
    lead_id: 'lead-003',
    coach_id: 'coach-matt',
    date: twoDaysAgo,
    time_block: 'morning',
    skill: 'pitching',
    day_number: 1,
    is_final_day: false,
    status: 'completed',
    created_at: lastWeek + 'T07:00:00Z',
    updated_at: twoDaysAgo + 'T17:00:00Z',
    coach_name: 'Matt Reynolds',
    coach_tier_display: 'S1',
    athlete_name: 'Ryan Chen',
    contact_name: 'David Chen',
    contact_phone: '+16155553456',
    athlete_age: 19,
    athlete_level: 'college',
    experience_start: lastWeek,
    experience_end: lastWeekEnd,
    skill_focus: 'pitching',
    experience_status: 'completed',
    duration_days: 4,
  },
  {
    id: 'slot-003',
    experience_id: 'exp-001',
    lead_id: 'lead-005',
    coach_id: 'coach-drew',
    date: today,
    time_block: 'afternoon',
    skill: 'hitting',
    day_number: 1,
    is_final_day: false,
    status: 'scheduled',
    created_at: yesterday + 'T10:00:00Z',
    updated_at: yesterday + 'T10:00:00Z',
    coach_name: 'Drew Anderson',
    coach_tier_display: 'S1',
    athlete_name: 'Carlos Martinez',
    contact_name: 'Robert Martinez',
    contact_phone: '+16155555678',
    athlete_age: 17,
    athlete_level: 'high_school',
    experience_start: nextWeek,
    experience_end: nextWeekEnd,
    skill_focus: 'pitching',
    experience_status: 'booked',
    duration_days: 4,
  },
  {
    id: 'slot-004',
    experience_id: 'exp-001',
    lead_id: 'lead-005',
    coach_id: 'coach-austin',
    date: today,
    time_block: 'morning',
    skill: 'pitching',
    day_number: 1,
    is_final_day: false,
    status: 'scheduled',
    created_at: yesterday + 'T10:00:00Z',
    updated_at: yesterday + 'T10:00:00Z',
    coach_name: 'Austin Blake',
    coach_tier_display: 'S2',
    athlete_name: 'Carlos Martinez',
    contact_name: 'Robert Martinez',
    contact_phone: '+16155555678',
    athlete_age: 17,
    athlete_level: 'high_school',
    experience_start: nextWeek,
    experience_end: nextWeekEnd,
    skill_focus: 'pitching',
    experience_status: 'booked',
    duration_days: 4,
  },
]

export function isPreviewMode(): boolean {
  return process.env.NEXT_PUBLIC_DEV_PREVIEW === 'true'
}
